### ISSUE TITLE
String translatable

### ISSUE THREAD

**Issue by krzysztofjeziorny** [donhauser/wagtail-photo-gallery#1]
It's an interesting project, I'll try it out. But just found out a string one would like to translate.

https://github.com/donhauser/wagtail-photo-gallery/blob/d70bcc879c53b651d5aa52acded7f19d567b8682/wagtail_photo_gallery/templates/blocks/photo_gallery.html#L13

**Comment by donhauser** [comment]
Every contribution is very welcome :)

I originally wrote this for a german website, but I thought it would be nice to share it.

You can either create a pull request if you like,
or I'll fix it my self when I got time.

Thanks for reporting anyhow :+1:

**Comment by donhauser** [comment]
Proper translation is now implemented in both, the code and the templates. So this is now fixed in version 0.1.1
