### ISSUE TITLE
Wagtail 5.0 not supported: `No module named 'wagtail.admin.edit_handlers'`

### ISSUE THREAD

**Issue by timobrembeck** [donhauser/wagtail-photo-gallery#7]
When trying to use this with wagtail 5.0, I get the following error (performing the initial migrations):
```
  File "/path/to/.venv/lib/python3.11/site-packages/wagtail_photo_gallery/models.py", line 8, in <module>
    from wagtail.admin.edit_handlers import HelpPanel, FieldPanel, ObjectList, TabbedInterface, InlinePanel, MultiFieldPanel
ModuleNotFoundError: No module named 'wagtail.admin.edit_handlers'
```
And the reason is pretty clear:

> The modules wagtail.core, wagtail.tests, wagtail.admin.edit_handlers and wagtail.contrib.forms.edit_handlers are removed.

– https://docs.wagtail.org/en/stable/releases/5.0.html#upgrade-considerations

So I think it would make sense to support the new version and also add a version specifier like `wagtail<6.0` or similar to `setup.py` to prevent breaking changes in the future and only allow installation after the breaking changes have been reviewed and the library is tested with the new release.

**Comment by donhauser** [comment]
Wagtail 4 and 5 are now supported as of version 0.1.0
Support for Wagtail 6 is planed, but requires changing ModelAdmin code, which is not migrated yet. (PRs for Wagtail 6 Snippets are welcome!)
